### PR TITLE
Use hooks for Panoptes data-fetching

### PR DESCRIPTION
**Pull request by eatyourgreens**
- replace `usePanoptes` with `useSubject` and `useWorkflow`, which fetch subjects and workflows with the new client (and SWR.)
- remove `store.workflow.fetchWorkflow` and `store.subject.fetchSubject`.

Follow-up to #98.

### CODE REVIEW

**Comment by shaunanoordin** [comment]
I can't seem to get this branch to run properly. 

- [Home page:](https://localhost:3000/) OK 👍 
- ❌ Workflow: page crashes with the error `Uncaught TypeError: store.workflow.fetchWorkflow is not a function`
  - [Example: WF 3438 staging](https://localhost:3000/view/workflow/3438)
  - I think the `WorkflowPage` is still using `fetchWorkflow()`
- ❌ Subject page: no data is fetched
  - both Subject and Workflow are stuck in the "Loading" state.
  - Network indicates that the Panoptes API is correctly pinged and both resources are fetched, but they don't seem to be processed and the app state doesn't move to the "Success" state.
  - [Example: Galaxy Zoo for Schools Subject](https://localhost:3000/view/workflow/40/subject/475202?env=production)
  - [Example: Virus Picker staging Subject](https://localhost:3000/view/workflow/3438/subject/134548)

The Workflow page should be an easy fix, but the Subject page not working is a bit perplexing. Going to check if it's just on my end.

**Comment by eatyourgreens** [comment]
@shaunanoordin I'm an idiot. The `usePanoptes` hook resets the subject and workflow stores on every render, so that the state is always empty and loading.

**Comment by eatyourgreens** [comment]
@shaunanoordin is it ok to merge this?

**Comment by eatyourgreens** [comment]
Oooooh, reviews aren't required for Zoo Notes so auto-merge will just automatically merge (without waiting.)

**Pull request merged**
